---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajeshtilwani3-node-sample-app-master
spec:
  selector:
    matchLabels:
      app: rajeshtilwani3-node-sample-app-master
  replicas: 1
  template:
    metadata:
      labels:
        app: rajeshtilwani3-node-sample-app-master
      annotations: 
        date: "+%H:%M:%S %d/%m/%y"
    spec:
      containers:
      - name: rajeshtilwani3-node-sample-app-master
        image: 715285876037.dkr.ecr.ap-south-1.amazonaws.com/rajeshtilwani3-node-sample-app-master:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rajeshtilwani3-node-sample-app-master
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rajeshtilwani3-node-sample-app-master
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rajeshtilwani3-node-sample-app-master
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:

  - host: rajeshtilwani3-node-sample-app-master.devops.humalect.com
    http:
      paths:
      - backend:
          serviceName: rajeshtilwani3-node-sample-app-master
          servicePort: 80
        path: /
